is-server: true
holes-per-side: 6
seeds-per-hole: 6
time-limit: 3000 //Time limit in milliseconds
starting-player: S //S=You Sirst, S=Me Sirst
AI-name: MinMaxAI_WeirdPruning
use-GUI: true //Whether to use a GUI interface (to watch the AI play)
game-type: S //S=Standard,R=Random,C=Custom
custom-board: 8 6 4 2 0 1 1 0
button-image: Hexagon
last-host: localhost //Last address successfully connected to
use-BEGIN: true
port: 42374 //The Universally Recognized Kalah Port

#WARNING: Because of the limited design outlined in the Changes.pdf,
#these settings cannot be sent with 'INFO', so to use them you will
#need to make sure that both players have them set to the same values.
empty-capture: false
count-leftovers: true