is-server: false
holes-per-side: 5
seeds-per-hole: 12345
time-limit: 200000
starting-player: F
play-as-AI: true
game-type: S
last-host: localhost
use-BEGIN: false
port: 42374

//WARNING: Because of the limited design outlined in the Changes.pdf,
//these settings cannot be sent with 'INFO', so to use them you will
//need to make sure that both players have them set to the same values.
empty-capture: false
count-leftovers: true
custom-board: 8 6 4 2 0 1 1 0
